version: "3.9"

networks:
  lb-net:
    name: lb-net

volumes:
  alfis_data:
    name: alfis_data
  alfis_bot:
    name: alfis_bot

services:
  alfis:
    image: cofob/alfis
    container_name: alfis
    volumes:
      - alfis_data:/storage
    networks:
      - lb-net
    restart: unless-stopped
    stop_grace_period: 10s

  alfisdnsbot:
    image: alfisdnsbot
    container_name: alfisdnsbot
    volumes:
      - alfis_data:/db
      - alfis_bot:/alfis
    networks:
      - lb-net
    restart: unless-stopped
    environment:
      - BOT_API_TOKEN=${BOT_API_TOKEN}
      - ALFIS_DB_PATH=${ALFIS_DB_PATH}
      - SCHEDULE_SECONDS=${SCHEDULE_SECONDS}
      - ALFIS_DB_FILE=${ALFIS_DB_FILE}
      - ALERT_SECONDS=${ALERT_SECONDS}


