version: "3.9"

networks:
  lb-net:
    name: lb-net

volumes:
  alfis_data:
    name: alfis_data

services:
  alfis:
    image: cofob/alfis
    container_name: alfis
    volumes:
      - alfis_data:/storage
    networks:
      - lb-net
    restart: unless-stopped
    stop_grace_period: 10s

  alfisdnsbot:
    image: alfisdnsbot
    container_name: alfisdnsbot
    volumes:
      - alfis_data:/db
    networks:
      - lb-net
    restart: unless-stopped
    environment:
      - BOT_API_TOKEN=${BOT_API_TOKEN}
      - ALFIS_DB_PATH=/db
      - SCHEDULE_SECONDS=60 #default 60
#      - ALFIS_DB_FILE="blockchain.db"
#      - ALERT_SECONDS=180


